version: "3"

services:
  api:
    platform: linux/amd64
    container_name: meuslares-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    mem_limit: 512m
    memswap_limit: 1g
    env_file: ./.env
    environment:
      - DB_PORT=${DB_PORT_DOCKER}
      - DB_HOST=${DB_HOST_DOCKER}
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - db
    networks:
      - meuslares-network
    
  interface:
    platform: linux/amd64
    container_name: meuslares-interface
    build: 
      context: ./interface
      dockerfile: Dockerfile
    volumes:
      - ./interface/src:/app/src
      - ./interface/public:/app/public
    mem_limit: 512m
    memswap_limit: 1g
    env_file: ./.env
    ports:
      - "${INTERFACE_PORT}:9001"
    networks:
      - meuslares-network

  db:
    image: postgres:15
    container_name: meuslares-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: America/Sao_Paulo
    ports:
      - "${DB_PORT}:5432"
    networks:
      - meuslares-network
    
networks:
  meuslares-network:
    driver: bridge

volumes:
  postgres_data:
